services:
  application:
    build: .
    depends_on: [database]
    networks:
      - backend
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/job_service
    ports:
      - '9000:9000'
  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=job_service
      - MYSQL_ROOT_PASSWORD=Godfather@2.0
    ports:
      - '3308:3306'
    networks:
      - backend
networks:
  backend: